/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : uartXbee.h
**     Project     : Drone-RTOS
**     Processor   : MKL25Z128VLK4
**     Component   : fsl_lpsci
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-07-11, 11:09, # CodeGen: 34
**     Contents    :
**         LPSCI_DRV_Init                - lpsci_status_t LPSCI_DRV_Init(uint32_t instance,lpsci_state_t *...
**         LPSCI_DRV_Deinit              - lpsci_status_t LPSCI_DRV_Deinit(uint32_t instance);
**         LPSCI_DRV_InstallRxCallback   - lpsci_rx_callback_t LPSCI_DRV_InstallRxCallback(uint32_t...
**         LPSCI_DRV_InstallTxCallback   - lpsci_tx_callback_t LPSCI_DRV_InstallTxCallback(uint32_t...
**         LPSCI_DRV_SendDataBlocking    - lpsci_status_t LPSCI_DRV_SendDataBlocking(uint32_t instance,const uint8_t *...
**         LPSCI_DRV_SendData            - lpsci_status_t LPSCI_DRV_SendData(uint32_t instance,const uint8_t *...
**         LPSCI_DRV_GetTransmitStatus   - lpsci_status_t LPSCI_DRV_GetTransmitStatus(uint32_t instance,uint32_t *...
**         LPSCI_DRV_AbortSendingData    - lpsci_status_t LPSCI_DRV_AbortSendingData(uint32_t instance);
**         LPSCI_DRV_ReceiveDataBlocking - lpsci_status_t LPSCI_DRV_ReceiveDataBlocking(uint32_t instance,uint8_t *...
**         LPSCI_DRV_ReceiveData         - lpsci_status_t LPSCI_DRV_ReceiveData(uint32_t instance,uint8_t *...
**         LPSCI_DRV_GetReceiveStatus    - lpsci_status_t LPSCI_DRV_GetReceiveStatus(uint32_t instance,uint32_t *...
**         LPSCI_DRV_AbortReceivingData  - lpsci_status_t LPSCI_DRV_AbortReceivingData(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file uartXbee.h
** @version 01.00
*/         
/*!
**  @addtogroup uartXbee_module uartXbee module documentation
**  @{
*/         
#ifndef __uartXbee_H
#define __uartXbee_H
/* MODULE uartXbee. */
/* Include inherited beans */
#include "clockMan1.h"
#include "osa1.h"
#include "Cpu.h"
#include "fsl_lpsci_driver.h"

/*! @brief Device instance number */
#define uartXbee_IDX UART0_IDX
/*! @brief Device instance number for backward compatibility */
#define FSL_UARTXBEE uartXbee_IDX
  
/*! Driver state structure without DMA */
extern lpsci_state_t uartXbee_State;
/*! External declaration of Rx buffer */
extern uint8_t uart_rxbuff[1];
    
/*! Interrupt service routine (ISR) prototype */    
void uartXbee_IRQHandler(void);    
  
/*! @brief Configuration declaration */
extern const lpsci_user_config_t uartXbee_InitConfig0;
    
#endif
/* ifndef __uartXbee_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
